### ISSUE TITLE
Errors when using Proguard

### ISSUE THREAD

**Issue by agatti** [pwittchen/ReactiveNetwork#121]
Hello,

  after updating from 0.5.2 to 0.6.0, my application cannot have Proguard applied to it anymore:

```
Warning: com.github.pwittchen.reactivenetwork.library.ReactiveNetwork$1: can't find superclass or interface io.reactivex.functions.Function
Warning: com.github.pwittchen.reactivenetwork.library.ReactiveNetwork$1: can't find referenced class io.reactivex.functions.Function
Warning: com.github.pwittchen.reactivenetwork.library.ReactiveNetwork$1: can't find referenced class io.reactivex.functions.Function
Warning: com.github.pwittchen.reactivenetwork.library.ReactiveNetwork$1: can't find enclosing method 'io.reactivex.Observable observeInternetConnectivity(int,java.lang.String,int,int)' in program class com.github.pwittchen.reactivenetwork.library.ReactiveNetwork
```

  I can work around that by adding `-dontwarn io.reactivex.functions.Function` and `-dontwarn com.github.pwittchen.reactivenetwork.library.ReactiveNetwork` to `proguard.pro`, but I'm not sure whether this is a symptom of something else.

**Comment by pwittchen** [comment]
Thanks for reporting this issue. It may be related to RxJava update because I bumped it from `1.1.9` to `1.2.1`. These warnings are related to `io.reactivex.functions.Function` and `io.reactivex.Observable`, which are elements of RxJava library.

**Comment by Sigvent** [comment]
any solution ?

**Comment by pwittchen** [comment]
Are you using the same version of RxJava dependency as the ReactiveNetwork library (`1.2.1`) in your main project?

**Comment by Sigvent** [comment]
@pwittchen : Yes and I added in my proguard to keep class in io.reactivex.functions.** + io.reactivex.Observable

**Comment by pwittchen** [comment]
I've noticed that here: https://github.com/requery/requery/issues/293 they have the same problem and they're using the same version of RxJava, so I guess for now the solution will be to configure `-dontwarn` statements for ProGuard on the library level. A quick fix is ProGuard configuration on the application level. I don't know if there's any better solution out there right now.

**Comment by Sigvent** [comment]
Alright !
Thank you for the fast answer.

**Comment by pwittchen** [comment]
I've tried to configure ProGuard, but it threw errors during compilation of sample Kotlin app:

```
/home/piotr/Development/android/projects/private/ReactiveNetwork/app-kotlin/src/main/kotlin/com/github/pwittchen/reactivenetwork/kotlinapp/MainActivity.kt
Error:(48, 36) Unresolved reference: state
Error:(49, 35) Unresolved reference: name
Error:Execution failed for task ':app-kotlin:compileDebugKotlin'.
> Compilation error. See log for more details
```

I'm not an expert with using ProGuard tool, so if anyone knows, how to configure it right, to avoid warnings and compilation errors in this case, please, let me know.

Here is a configuration I tried to use:

```
-dontwarn io.reactivex.functions.Function.**
-dontwarn com.github.pwittchen.reactivenetwork.**
-keep class com.github.pwittchen.reactivenetwork.library.** { *; }
-keepclassmembers class com.github.pwittchen.reactivenetwork.library.** {
   public *;
}
```

**Comment by lman** [comment]
**fix:**

```
#ReactiveNetwork
-dontwarn com.github.pwittchen.reactivenetwork.library.ReactiveNetwork
-dontwarn io.reactivex.functions.Function

**Comment by pwittchen** [comment]
Okay. Done. I've added section [ProGuard configuration](https://github.com/pwittchen/ReactiveNetwork#proguard-configuration) in README.md and updated ProGuard and Gradle configuration for the sample apps to verify it on CI.
