### ISSUE TITLE
Improve unit tests, which use Mockito

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#124]
Replace `mock(...)` methods with annotations, add proper `setUp()` and `tearDown()` methods.
Reference: http://stackoverflow.com/questions/36082370/i-need-both-robolectric-and-mockito-in-my-test-each-one-proposes-their-own-test

**Comment by Kisty** [comment]
I think from the SO post, you can either use the `MockitoRule` or use the manual `setUp()` and `tearDown()` methods. You don't have to use both. So using just a `MockitoRule` should suffice. 

That is, unless I've missed something with what you want to do in `setUp()` and `tearDown()`.

**Comment by pwittchen** [comment]
I wanted to add `@Spy` and `@Mock` annotations instead of manually calling `mock(...)` and `spy(...)` methods. You can take a look at PR.

**Comment by Kisty** [comment]
What I meant is that by using a [`MockitoRule`](http://site.mockito.org/mockito/docs/current/org/mockito/junit/MockitoRule.html), you don't need the call to `initAnnotations()` in `setUp()`. Also the rule does a call to `validateMockitoUsage()` in `tearDown()`. It'll be fine as is though.

**Comment by pwittchen** [comment]
@Kisty I've somehow missed feature with `@Rule` annotation. It's added in PR #131. I think it's a better approach than manually calling `MockitoAnnotations.initMocks(this)` method.

Thanks!
