### ISSUE TITLE
Error in preconditions

### ISSUE THREAD

**Issue by aperfilyev** [pwittchen/ReactiveNetwork#129]
Hey! You have an error [there](https://github.com/pwittchen/ReactiveNetwork/blob/master/library/src/main/java/com/github/pwittchen/reactivenetwork/library/Preconditions.java#L74)

**Comment by pwittchen** [comment]
Thanks for pointing this out!

**Comment by pwittchen** [comment]
We need to add unit tests for concrete API versions via `@Config` annotation to avoid regression of this bug in the future and for better testing of the strategies.

Reference: http://stackoverflow.com/questions/20541630/does-robolectric-support-api-level

**Comment by pwittchen** [comment]
Fixed! :star2:
