### ISSUE TITLE
Add other network stautuses

### ISSUE THREAD

**Issue by josias1991** [pwittchen/ReactiveNetwork#13]
Add the following to detect WIFI connectivity status, the same way you did in the NetworkingEvents Library:

    WIFI_CONNECTED("connected to WiFi"),
    WIFI_CONNECTED_HAS_INTERNET("connected to WiFi (Internet available)"),
    WIFI_CONNECTED_HAS_NO_INTERNET("connected to WiFi (Internet not available)"),

for wifi you only have
WIFI_CONNECTED("connected to WiFi")

**Comment by pwittchen** [comment]
Thanks for reporting the issue. This library doesn't have these statuses, because it's simpler. I'll take a look on that and probably add mentioned statuses.

**Comment by pwittchen** [comment]
Final behavior of ReactiveNetwork should be like described in the issue: https://github.com/pwittchen/NetworkEvents/issues/87
We also need to add method like `enableInternetCheck()` or something similar for users who want to activate this potential feature.

**Comment by josias1991** [comment]
Awesome man, thanks for keeping it in mind!

**Comment by pwittchen** [comment]
Done. It will be available in the next release.

**Comment by josias1991** [comment]
You my friend, are awesome!

**Comment by pwittchen** [comment]
You're welcome.
You can find more info about new feature here: https://github.com/pwittchen/ReactiveNetwork#enabling-internet-check.

Release of version 0.1.0 is on the way.
