### ISSUE TITLE
Use Java 8 language features in sample apps

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#132]
Use Java 8 language features in sample apps. Especially lambdas with RxJava code.
Reference: https://developer.android.com/guide/platform/j8-jack.html

**Comment by epicstar** [comment]
Another recommendation is to use retrolambda since jack isn't "production ready" yet: https://github.com/orfjackal/retrolambda

**Comment by Kisty** [comment]
That is true, however it's only for the demo app, so wouldn't be part of the library. However, it would be a template on how to use the library. Retrolambda seems pretty solid and an industry standard by many at present.

**Comment by pwittchen** [comment]
I don't want to include jack or retrolamba in the library. Developers can make their own choice. I just want to upgrade sample app. :-)

I don't know the current state of the retrolambda, but I had some problems with it some time ago. E.g. after changing code including retrolambda I needed to perform clean before the application build because I was receiving runtime exceptions and my apps were crashing. In addition, Jack is official Google recommendation.

**Comment by pwittchen** [comment]
I tried to make it work, but it does not work out of the box and it's not usable for now. I'm closing this issue and we can get back to this topic, when Jack will be stable.
