### ISSUE TITLE
Create releasing guidelines

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#141]
Create releasing guidelines in `RELEASING.md` file.

**Comment by epicstar** [comment]
I would recommend to use a Wiki page for guidelines instead. That way, you don't have to do commits for each change to the release process.

**Comment by pwittchen** [comment]
Thanks for the suggestion, but I'd like to keep this information inside Git repository and keep tracking of changes. Moreover, I don't think that this process will change a lot. I just want to have it documented somewhere (not only in my head ;)). Maybe it will change if we manage to automate it in few parts or move this process to CI.

**Comment by pwittchen** [comment]
Done.
