### ISSUE TITLE
Feature request: Observe Airplane Mode

### ISSUE THREAD

**Issue by consp1racy** [pwittchen/ReactiveNetwork#150]
And deliver it as part of the `Connectivity` bundle.

**Comment by pwittchen** [comment]
Hi,

Thanks for creating that issue! To be honest, I already thought about that. I wondered that it may be a good idea for a separate library. Airplane mode is not related to networking issues and user needs to enable it explicitly. Moreover, it's possible to connect to WiFi network when airplane mode is on.

Regards,
Piotr

**Comment by consp1racy** [comment]
Hi, 
now come to think of it, airplane mode does affect network but not only network. It makes sense not just making it another flowable but releasing it as a separate artifact as well (in case there isn't an existing implementation.)

`concatLatest` could be a friend if you need to observe network and airplane mode, what do you think?

**Comment by pwittchen** [comment]
When we have a separate Observable or Flowable, we can later combine it with existing Observables responsible for observing network or Internet connection (e.g. with `concat(...)` operator) in the concrete solution, so we'll be able to monitor both airplane mode and network connectivity. That's the approach, which leverages the power of RxJava and its basic concept of composition of streams.

**Comment by consp1racy** [comment]
Let's say I wanted to show a Snackbar when
 * connectivity is on (Connected.)
 * airplane mode is enabled (Turn off Airplane mode.)
 * network is down (No connection available.)

In such case I'd need both outputs at the same time. The flowable should be built with `combineLatest` in mind and use a `startWith` operator. ReactiveNetwork already does it.

**Comment by pwittchen** [comment]
I see, the only thing, which is missing is monitoring of airplane mode and combining it with existing Observables. Remaining functionality is already available and ready to use.

**Comment by Kisty** [comment]
I agree that this should probably be its own library or an easy way to switch off. Although, I won't say it won't be useful to know if the user is in airplane mode so to offer a quick fix for user to get connection.

**Comment by pwittchen** [comment]
@consp1racy @Kisty 
I've made a separate library for observing Airplane Mode with RxJava2. I think it resolves this feature request.

Link to this project: https://github.com/pwittchen/ReactiveAirplaneMode

Regards,
Piotr
