### ISSUE TITLE
Subscription for connectivity status is not being called

### ISSUE THREAD

**Issue by wrparrish** [pwittchen/ReactiveNetwork#17]
*Update*     I  neglected to call enableInternetCheck()  on the ReactiveNetworkObject.

**Comment by pwittchen** [comment]
I've made some small changes. You can read about them in the latest release notes here: https://github.com/pwittchen/ReactiveNetwork/releases/tag/v0.1.0

I've checked sample app from this repository (https://github.com/pwittchen/ReactiveNetwork/tree/master/app) a moment ago and it works fine. 

Moreover, in version 0.0.3 I've removed one of the BroadcastReceiver filter: `WifiManager.WIFI_STATE_CHANGED_ACTION`. Release notes for 0.0.3: https://github.com/pwittchen/ReactiveNetwork/releases/tag/v0.0.3.

This filter causes calling subscriber every time, when user turns on WiFi. Now, we have only `ConnectivityManager.CONNECTIVITY_ACTION` filter. It means that, we will receive an event **only when user will be connected to any WiFi network**. Maybe this is your issue?

**Comment by pwittchen** [comment]
`enableInternetCheck()` method is required only in the case, when you want to check if given WiFi network is connected to internet.

Is it working now in your app?

**Comment by wrparrish** [comment]
I think so,

I am getting the calls now,  thank you!  The change you made makes sense,
and explains the difference in what I was seeing upon upgrade.

**Comment by pwittchen** [comment]
Great!

Thanks for reporting the issue and adding new comment.
I think, we can close this issue for now.

If you encounter any troubles or doubts in the future, feel free to create another issue.
Any kind of feedback is appreciated

Happy coding,

Regards,
Piotr
