### ISSUE TITLE
Should I be concerned (could not unregister receiver)

### ISSUE THREAD

**Issue by juanmendez** [pwittchen/ReactiveNetwork#190]
First and foremost thanks for creating this library. It makes the job a lot easier having less code to write.

As I have one subscription unregistering, I get to see this stack error:

`could not unregister receiver java.lang.IllegalArgumentException: Receiver not registered: com.github.pwittchen.reactivenetwork.library.network.observing.strategy.MarshmallowNetworkObservingStrategy$2@a8fbe88`

I know you attempt to unregister here: https://github.com/pwittchen/ReactiveNetwork/blob/RxJava1.x/library/src/main/java/com/github/pwittchen/reactivenetwork/library/network/observing/strategy/MarshmallowNetworkObservingStrategy.java#L98

Should I be concerned about this message or just ignore it? Thank you.

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. Can you provide steps to reproduce this problem?
This may happen, when you forget to unsubscribe (for rx2: dispose) your subscription. If you're using this library in the `Activity`, call `unsubscribe()`  method on your `Subscription` object in `onPause()` method. In the case of `Service`, you should call it in `onDestroy()` method.

Regards,
Piotr

**Comment by juanmendez** [comment]
Sure, this is a class I wrote and whose connect and disconnect are called by onStart() and onPause() handlers of a fragment. I noticed the error occurs once I call onDisconnect() right when I unsubscribe. I am using RxJava 1.x. I am making use of a singleton, and possibly that is what could be wrong, rather than recreate the observable each time. (I'm using Dagger that's why I left it as a singleton dependency). Thanks a lot for your help.

In my dagger module
```java
@Singleton
@Provides
public NetworkService getNetworkService() {
    return new DroidNetworkService( app );
}
```

```java
public class DroidNetworkService implements NetworkService {

    Context context; //application context
    Observable<Connectivity> observable;
    Boolean connected = false;

    /**
     * each subscription is mapped along with a key object.
     * in this way is easy to unsubscribe each.
     */
    HashMap<Object, Subscription> subscriptionHashMap = new HashMap<>();

    public DroidNetworkService(Context context) {
        this.context = context;

        observable = ReactiveNetwork.observeNetworkConnectivity(context)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread());
    }

    @Override
    public boolean isConnected() {
        return connected;
    }

    @Override
    public void connect(Object keyObject, NetworkResponse response) {

        //one subscription per keyObject
        disconnect(keyObject);

        Subscription subscription = observable.subscribe(connectivity -> {
            response.onStatusChanged( connected = connectivity.isAvailable() );
        }, throwable -> {
            throwable.printStackTrace();
        });

        subscriptionHashMap.put( keyObject, subscription );
    }

    @Override
    public void disconnect(Object keyObject) {
        connected = false;
        Subscription subscription = subscriptionHashMap.get( keyObject );

        if (subscription != null && !subscription.isUnsubscribed()) {
            subscriptionHashMap.remove( keyObject ); //ERROR happens here. 
            subscription.unsubscribe();
        }
    }
}
```

**Comment by pwittchen** [comment]
Please note, Android Fragments have more complicated LifeCycle than Activities. I haven't tested this library with Fragments and to be honest, I avoid using them due to their design, which makes them hard to use. In the case of Fragments, it may be required to subscribe and unsubscribe Observables in different methods than Activity. Check out this post: https://stackoverflow.com/a/40804923/1150795. It may be helpful.

It may be required to create a subscription in `onAttach(Context context)` method and unsubscribe them in `onDetach()` method of the Fragment.

**Comment by juanmendez** [comment]
hi, I tried it like that and still got the same error. But like you said this is to do with fragments lifecycle than any issue with your library. If I find a solution I will reopen the case with the solution. Thanks.

**Comment by juanmendez** [comment]
I fixed it. What did I do?
I removed the singleton from the dagger module.

```java
@Provides
public NetworkService getNetworkService() {
    return new DroidNetworkService( app );
}
```

And everything on that class remained the same.  I still do unsubscribe for preventing memory leak. Thanks a lot :)

**Comment by pwittchen** [comment]
Great to hear you solved it!

Kind Regards,
Piotr
