### ISSUE TITLE
Problem on Android 4.4.2

### ISSUE THREAD

**Issue by PitipongXYZ** [pwittchen/ReactiveNetwork#207]
I've used this code on Android API 4.4.2 

```java
ReactiveNetwork.observeNetworkConnectivity(getActivity())
 .subscribeOn(Schedulers.io())
 .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<Connectivity>() {
                    @Override public void accept(final Connectivity connectivity) {
                        if (connectivity.isAvailable()){
                            // Do something 
                        } else {
                            // Do something 
                        }
                    }
                });
```

It's force close and show this error in logcat

```java
java.lang.NoClassDefFoundError: io.reactivex.plugins.RxJavaPlugins
at io.reactivex.Observable.create(Observable.java:1562)
at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.PreLollipopNetworkObservingStrategy.observeNetworkConnectivity(PreLollipopNetworkObservingStrategy.java:48)
```

Thank in advance

**Comment by pwittchen** [comment]
Hi,

It looks like problem with Gradle, ProGuard or MultiDex. Try to add RxJava2 dependency explicitly to your project:

```groovy
compile 'io.reactivex.rxjava2:rxjava:2.1.2'
```

and then compile it.

Reference: https://realm.io/docs/java/latest/#jackson-databind

It also may be an issue with MultiDex and `rx.Observable` class may not be included in the primary `*.dex` file.

You can multidex support by adding the following dependency to your `build.gradle` project:

```groovy
compile 'com.android.support:multidex:1.0.1'
```

and then compile it.

Reference: https://github.com/ReactiveX/RxAndroid/issues/263

I hope it helps.

**Comment by PitipongXYZ** [comment]
Thank you for your answer, But it doesn't work. T-T

**Comment by pwittchen** [comment]
@PitipongXYZ I checked StackOverflow. See this solution: https://stackoverflow.com/a/37632531/1150795

After adding:

```groovy
compile 'com.android.support:multidex:1.0.1'
```

to your `build.gradle` file, you also need to define your own instance of an `Application`, which needs to extend `MultiDexApplication` like here:

`AndroidManifest.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.multidex.myapplication">
    <application
        ...
        android:name="YourAppName">
        ...
    </application>
</manifest>
```

`YouAppName.java` source:

```java
public class YouAppName extends MultiDexApplication {
  // ...
}
```

**Comment by PitipongXYZ** [comment]
**Wow, it's working now, You're the man, Thanks!**

**Comment by pwittchen** [comment]
Great! I think we can treat this issue as resolved. 
Maybe later I'll add your use case to the documentation if someone else will have a similar problem.
