### ISSUE TITLE
emit current ConnectionStatus on subscription

### ISSUE THREAD

**Issue by adennie** [pwittchen/ReactiveNetwork#21]
a feature request - could you emit the current ConnectionStatus at subscription time?

**Comment by pwittchen** [comment]
Thank you for reporting this issue. Actually current `ConnectionStatus` is emitted at subscription time in the following cases:
- device is connected to WiFi network
- device is connected to mobile network

The only situation, when `ConnectionStatus` is not emitted at subscription time is when device is offline (is not connected to any network).

I've tested it a few seconds ago. If you find it useful, we can add offline status at subscription time as well.

**Comment by pwittchen** [comment]
I've added emission of `OFFLINE` status when user is not connected to any network. It will be available in the next release. If something will still work in a wrong way, please create another issue or reopen this issue.
