### ISSUE TITLE
Automate generating and publishing release notes & changelog

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#227]

**Comment by Kisty** [comment]
Would be very interesting in how you achieve this! I guess take it from `git log`? I think some manual tidying would be needed if that's the case.

**Comment by pwittchen** [comment]
Right now, it's just an idea, but I'd like to take commits between tag from the latest release and now (via git log) and then generate an update in `CHANGELOG.md` file and push it to the repository. In the future, I'd like to use GitHub API to create the same update in the GitHub releases. I think I can create a bash or python script (or scripts) for that.

**Comment by pwittchen** [comment]
Right now, we're abandoning this. We can come back to this idea in the future.
Up to now, we have automated JavaDoc generation and website generation (based on `README.md`).
