### ISSUE TITLE
Connectivity return incorrect results ?

### ISSUE THREAD

**Issue by chihung93** [pwittchen/ReactiveNetwork#230]
OS: Android 7.0 
Emulator: Nexus S - Nougat API 24 

When I turn off wifi on my phone, I return the result:
connectivity.isAvailable() == true

It happens when turn on/off Wifi on phone several times.

```java
ReactiveNetwork.observeNetworkConnectivity(this)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.newThread())
                .subscribe(new Consumer<Connectivity>() {
                    @Override public void accept(final Connectivity connectivity) {
                        EventBus.getDefault().post(new NetworkEvent(connectivity.isAvailable()));
                    }
                });
```

**Comment by pwittchen** [comment]
Thanks for reporting this issue.

This issue may be related to proxy or emulator configuration. I've tested it on real devices with a regular network connection and it worked fine. We can investigate proxy and emulator issue, but it may be system related thing.

**Comment by chihung93** [comment]
it happens on this real device :

OS: Android 5.0
Real Device: Jacs - ANDROID PoE TOUCH DEVICES

**Comment by pwittchen** [comment]
I've analyzed your code once again. Please note, you're using [NetworkInfo#isAvailable()](https://developer.android.com/reference/android/net/NetworkInfo.html#isAvailable()) method. According to the documentation it "Indicates whether network connectivity is possible". Connectivity is possible, so the value is `true`. It's correct behavior. If you want to check if you're connected to the network or not, please use [NetworkInfo#getState()](https://developer.android.com/reference/android/net/NetworkInfo.html#getState()) method. In ReactiveNetwork, you can access it via `Connectivity#getState()` method. You can view available states in [NetworkInfo.State](https://developer.android.com/reference/android/net/NetworkInfo.State.html) documentation. E.g. it can be `CONNECTED`, `DISCONNECTED`, `IDLE` and so on.

**Comment by chihung93** [comment]
And this lib so cool.
Thank you so much @pwittchen.

**Comment by pwittchen** [comment]
Ok. When everything is clear, then we can close this issue :).

**Comment by maweilong** [comment]
Hi foreign beauty

**Comment by aldocano** [comment]
Im sorry for reopening this issue but i have a question that is similar to it. Please check the code below and i struggle with it because of the incorrect value it returns. Because i do have internet connection and the library return false multiple times. 

```java
    Disposable rec = ReactiveNetwork.observeInternetConnectivity(new SocketInternetObservingStrategy(), "https://google.com")
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(isConnectedToHost -> {
                if (isConnectedToHost) {
                    getApp().setConnected(true);
                    if(dialog!=null){
                        dialog.dismiss();
                    }
                } else {
                    getApp().setConnected(false);
                    showInternetDialog();
                }
            });
```

**Comment by pwittchen** [comment]
Hi @aldocano,

In order to help you, I need more details. In standard scenario and setup, this code will work correctly. There must be something specific with your network, device or app.

**Comment by aldocano** [comment]
I happens in all devices, while i watch a online video in spans the dialog of no internet connection, i dont know why, because the device has continuous internet connection.

**Comment by chihung93** [comment]
@aldocano Al
I think it pings to an IP address continuously so it will be blocked for a short time.

**Comment by aldocano** [comment]
Which one is the better way to continuously check the internet connection?

**Comment by pwittchen** [comment]
If it's not necessary, it's better to check connectivity **only once**.
Read more here: https://github.com/pwittchen/ReactiveNetwork#checking-internet-connectivity-once
You can observe connectivity continuously if you really need this.

**Comment by aldocano** [comment]
Sorry for late response, i need to continuously check it, maybe pinging server returns some timeouts and therefore it displays the not connected dialog.?

**Comment by pwittchen** [comment]
Then you should use method with `observe` prefix. It's possible that server returns timeouts. It's also possible that you are using a proxy or network, which controls traffic and blocks many similar requests to avoid request flood, DoS, etc. You can try to set larger ping interval in milliseconds, which may fix this issue. It's possible with the library API. Default ping interval is 2000 ms (= 2 s). By the way, I have plans to make API for internet observing customisations more convenient.

**Comment by aldocano** [comment]
The server is google firebase server url. Strange that this occurs in strange conditions.
Can you show an example with the observe prefix and also the larger ping interval.

**Comment by pwittchen** [comment]
Sure.

You can use the following observable:

```java
Observable<Boolean> observeInternetConnectivity(int interval, String host, int port, int timeout)
```

For example:

```java
Disposable rec = ReactiveNetwork.observeInternetConnectivity(5000, "https://google.com", 80, 1000)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(isConnectedToHost -> {
     			// ...
            });
```

You can find more methods here: https://github.com/pwittchen/ReactiveNetwork#observing-internet-connectivity

I know, this API became unconveninent when number of parameters and different variantions grew, but I have plan to fix this.

**Comment by aldocano** [comment]
Thank you for the help i will try and let you know if there is any difference. Thanks.

**Comment by pwittchen** [comment]
There's no further discussion in more than one month, so I'm closing it.
