### ISSUE TITLE
How to unregisterReceiver with com.github.pwittchen:reactivenetwork-rx2:0.9.1 version?

### ISSUE THREAD

**Issue by PitipongXYZ** [pwittchen/ReactiveNetwork#245]
Hi there, I got this error message

> Activity has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$2@3809674 that was originally registered here. Are you missing a call to unregisterReceiver()?

My app not crash but how to call unregisterReceiver() for fix this?

Thank in advance.

**Comment by pwittchen** [comment]
To unregister receiver, you should dispose an Observable. E.g. in the case of the Activity, when you create an Observable somewhere (let's say in `onResume()` method), you should dispose it in `onPause()` method. It's a general rule regarding working with reactive data types on Android.

If you are looking for examples, take a look at the sample app here: https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/app/src/main/java/com/github/pwittchen/reactivenetwork/app/MainActivity.java

**Comment by PitipongXYZ** [comment]
Thanks, It very helpful for me.
