### ISSUE TITLE
Feature Request: Initial state when subscribing?

### ISSUE THREAD

**Issue by timrijckaert** [pwittchen/ReactiveNetwork#246]
Hi, 

Maybe I have not stumbled upon this in the documentation, but I can't seem to figure out how to get the initial state of the network info when subscribing on the stream.

It seems quite obvious to me the flow looks like this when subscribing:
1. Initial state
2. Changes

Or is there any equivalent to the `ReactiveNetwork.checkInternetConnectivity()` for `NetworkInfo`?

Thanks in advance.

**Comment by pwittchen** [comment]
Hi,

I don't really understand the question. When you call:

```java
ReactiveNetwork.observeNetworkConnectivity(context);
```

then you'll get an initial network state when subscribing and you'll be updated whenever connectivity changes.

Do you need to check network connectivity once without being updated later when connectivity will change? `ReactiveNetwork.checkInternetConnectivity()` returns RxJava2 `Single` type and then finishes emission of the data on the stream.

Moreover, initial state on the RxJava stream can be always achieved with `startWith(...)` operator. Actually, I'm using this operator inside the library.

**Comment by timrijckaert** [comment]
Ok my bad :)

**Comment by pwittchen** [comment]
No problem. I just wasn't sure about your use case and I thought maybe you needed something what the library does not offer :-).
