### ISSUE TITLE
Can ReactiveNetwork run on background ? 

### ISSUE THREAD

**Issue by TasTugberk** [pwittchen/ReactiveNetwork#261]
Hi, first of all thanks for such a good library. I'd like to use this library in the background, because I need to transfer local variables to server whenever connection arrives.
Thanks in advance.

**Comment by pwittchen** [comment]
Hi,

Sure. You can run it the background. If by "background" you mean inside Android Service, then of course it can be done. It doesn't matter when you call it (Activity or Service). If you would like to pass network monitoring to another thread via Scheduler, you can also do it with RxJava.

Regards,
Piotr

**Comment by TasTugberk** [comment]
I got it, thank you.
