### ISSUE TITLE
Observable.create alternative in tree-shaking

### ISSUE THREAD

**Issue by wjljack** [pwittchen/ReactiveNetwork#262]
I need tree-shaking like
`import { zip } from 'rxjs/observable/zip';`
to replace Observable.zip
but I can't find Observable.create ,when I use 
```javascript
import {Observable} from 'rxjs'
Observable.create()
```
it's import all prototypes in Observable and can't tree-shaking...

**Comment by wjljack** [comment]
I need a function to customize an Observable.

**Comment by pwittchen** [comment]
Hello.

I don't really know why are you providing sample code snippets in JavaScript while this project is a Java library :-).

Regards,
Piotr

**Comment by pwittchen** [comment]
I guess it's a mistake, so I'm closing this issue. If you have any questions regarding this project, you can create a new issue.
