### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by lovetomatoo** [pwittchen/ReactiveNetwork#265]
I want get the network change when my app is in background, so I add listener in `onCreate()` method, remove the listener in `onDestroy()` method. Then, mobile to wifi. I can't get a call back.

**Comment by pwittchen** [comment]
Hi,

It's not a bug. If you want to have network monitoring in the background, you should put subscription into the Android `Service` - not an `Activity`. It should work and have tested it some time ago. You shouldn't get any callback from the `Activity` when application is in the background.

Regards,
Piotr

**Comment by lovetomatoo** [comment]
@pwittchen Hi,
thank u for your answer. but I don't want to use Android Service. I tested again, I can get a call back, but it was slow, about 5 second. I don't want use Service that although  my app in background, it will alive always.

**Comment by pwittchen** [comment]
Honestly, I'm not sure if there's any way to write a code for Android which runs while app is in background other than using a `Service`. Code within the `Activity` is executed while `Activity` is active and within its lifecycle. It's related to Android system design - not this library.

**Comment by lovetomatoo** [comment]
I know that no way can keep app alive when it's in background. I only test when it alive in background, There is no timely give call back  when network from mobile to wifi. My way of test it is: First,call api "ReactiveNetwork.observeNetworkConnectivity" in onCreat not in onResume(I don't want to call this api evertime in onResume); Second,go to Setting page to change network form mobile to wifi. 5 second later, I can get a call back that network change to wifi.
I think 5 sencond is to long. It is my question.

**Comment by pwittchen** [comment]
If you don't want to call a web service every time, think about caching your response and call it when the data becomes stale (according to your strategy). This delay may depend on your system or a specific device. There's no 5 seconds delay coded in the library. We are getting new information as soon as we receive callback from the `BroadcastReceiver`. This library simply wraps default Android mechanisms and we have no control over the time of receiving this information. We can only decide how to handle it and what to do next.

**Comment by lovetomatoo** [comment]
Thank you very much.
