### ISSUE TITLE
android.os.NetworkOnMainThreadException on Pre-Lollipop devices

### ISSUE THREAD

**Issue by kuzmenok** [pwittchen/ReactiveNetwork#273]
PreLollipopNetworkObservingStrategy emits Connectivity in the main thread. No matter what flow I indicated. 
So that code will crash with NetworkOnMainThreadException:

```java
ReactiveNetwork.observeNetworkConnectivity(context)
        .flatMapSingle {
            if (it.state == NetworkInfo.State.CONNECTED) {
                ReactiveNetwork.checkInternetConnectivity()
            } else {
                Single.just(false)
            }
        }
        .subscribeOn(Schedulers.io())
```

Anyway, the lib is awesome :) Thanks!

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. Are you sure?
When you call something like that:

```java
ReactiveNetwork.observeNetworkConnectivity(context)
        .flatMapSingle {
            if (it.state == NetworkInfo.State.CONNECTED) {
                ReactiveNetwork.checkInternetConnectivity()
            } else {
                Single.just(false)
            }
        }
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(...);
```

Connectivity should be monitored in the background thread and result should be received in the main thread. Nevertheless, `observeConnectivity` methods do not rely on any network operations. They just wrap `BroadcastReaceivers` or Network Callbacks from Android API. Possibility of `NetworkOnMainThreadException` may be feasible in `observeInternetConnectivity` methods, but I haven't encountered it there.

**Comment by kuzmenok** [comment]
Yeah, I caught NetworkOnMainThreadException on call `ReactiveNetwork.checkInternetConnectivity()`. 
As I know, `BroadcastReceiver`'s method `onReceive` is called on the main thread, so the chain continues executing on the main thread. I just expected that chain will work on io-thread.

I think it would be great to call `emitter.onNext(Connectivity.create(context))` in the thread in which the method `observeNetworkConnectivity` worked.

**Comment by pwittchen** [comment]
`ReactiveNetwork.checkInternetConnectivity()` will be executed in the main thread as long as you won't tell it to be executed on another thread via `subscribeOn(...)` method.

**Comment by kuzmenok** [comment]
Ok. Seems there is misunderstanding :) I meant...
Let’s look at that example: 
```
ReactiveNetwork.observeNetworkConnectivity(context)
        .flatMapSingle {
            if (it.state == NetworkInfo.State.CONNECTED) {
                ReactiveNetwork.checkInternetConnectivity()
            } else {
                Single.just(false)
            }
        }
        .subscribeOn(Schedulers.io())
```
A block of code in the` flatMapSingle` runs on MainThread on Api < 21. And on RxThread on API 21+
In my opinion, there must be a consistency between API versions
P.S. It's not critical. We call `checkInternetConnectivity` in the background now) So the issue can be closed, I think

**Comment by consp1racy** [comment]
Broadcast receiver is run on the main thread but emissions must happen on the correct thread. One way is to use serialized subjects.

**Comment by luizgrp** [comment]
I'm facing exactly the same issue described by @kuzmenok when using `observeNetworkConnectivity`:

> block of code in theflatMapSingle runs on MainThread on Api < 21. And on RxThread on API 21+

I asked a question in [Stackoverflow](https://stackoverflow.com/questions/51288698/emit-values-on-the-thread-that-chain-is-subscribed-to), generalising the problem as I see it's not specific to this library but the fact that BroadcastReceiver.onReceive is called on the main thread.

@consp1racy could you please elaborate your suggestion? maybe with some examples.. I'm happy to try to fix it

**Comment by rajda** [comment]
Using observeOn instead of subscribeOn helped me in this case.

```java
ReactiveNetwork
        .observeNetworkConnectivity(context)
        .observeOn(Schedulers.io())
        .flatMapSingle {
            if (it.state == NetworkInfo.State.CONNECTED) {
                ReactiveNetwork.checkInternetConnectivity()
            } else {
                Single.just(false)
            }
        }
```

**Comment by gus-sky** [comment]
yeah there are ways around it, I believe you could also fix this way:

```
ReactiveNetwork.observeNetworkConnectivity(context) 
  .flatMapSingle { 
    if (it.state == NetworkInfo.State.CONNECTED) { 
      ReactiveNetwork.checkInternetConnectivity()
        .subcribeOn(Schedulers.io()) 
    } else {
      Single.just(false) 
    } 
}
```

but it would be nice to have consistency between across different API versions.

btw thanks for this amazing lib 👍
