### ISSUE TITLE
Network signal levels

### ISSUE THREAD

**Issue by EzeroVivanco** [pwittchen/ReactiveNetwork#282]
Hi, this library is really good.

I just have a question that I'm not able to solve. Is there a way to get the network (mobile data) signal level, similar to what can be done on ReactiveWifi library?

**Comment by pwittchen** [comment]
Hi,

I think it should be possible, but this library doesn't have such functionality. It's good idea for a separate tiny library. If you would like to monitor signal level (strength) of the mobile network, please take a look at the [`TelephonyManager`](https://developer.android.com/reference/android/telephony/TelephonyManager) from the Android API.

Regards,
Piotr

**Comment by EzeroVivanco** [comment]
Oh, thanks for the suggestion.
I'll take a look on it.

Regards.

**Comment by pwittchen** [comment]
I think, it's clear now and there's no further discussion, so I'm closing it.
