### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by smallwood69** [pwittchen/ReactiveNetwork#294]
org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'https://jitpack.io/com/github/pwittchen/reactivenetwork-rx2/2.1.0/reactivenetwork-rx2-2.1.0.pom'. Received status code 401 from server: Unauthorized

**Comment by pwittchen** [comment]
Hi,

I'm not publishing this library via JitPack, but via Maven Central. Please, ensure you're able to download artfiacts from Maven Central Repository. You should have something like that in your gradle config:

```groovy
repositories {
  mavenCentral()
  // other sources also goes there...
}
```

**Comment by pwittchen** [comment]
There's no further reply, so I suppose you resolved it.
