### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [pwittchen/ReactiveNetwork#296]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by pwittchen** [comment]
Hi,

Thanks for your message and proposal. You can prepare a logo for the project if you would like to. If it will be simple and neat, I can accept it as a project logo, but I cannot promise that.

Regards,
Piotr

**Comment by mansya** [comment]
hi sir. sorry about a long time. I have designed the logo for this project. Are you interested in using it? if yes. which one do you choose? 
![reactive network](https://user-images.githubusercontent.com/33461607/45588517-2aafa600-b940-11e8-9afd-fab33435d43d.png)

**Comment by pwittchen** [comment]
Hi,

I appreciate your effort and work, but if I add a logo to my project, I would go with something simpler, less "rounded" and less "shiny", so for now, project can be without logo.

Thanks again and all the best!

Regards,
Piotr
