### ISSUE TITLE
Problem when receiving internet connectivity in Android P (API 28)

### ISSUE THREAD

**Issue by danielbeleza** [pwittchen/ReactiveNetwork#299]
Hi guys! Great job with this lib! 

I just wanted to report a small issue that I'm having while receiving internet connectivity.

I'm using the following:

            return ReactiveNetwork.observeInternetConnectivity(InternetObservingSettings
                    .initialInterval(DEFAULT_INITIAL_PING_INTERVAL_IN_MS)
                    .interval(DEFAULT_PING_INTERVAL_IN_MS)
                    .host(DEFAULT_PING_HOST)
                    .port(DEFAULT_PING_PORT)
                    .timeout(DEFAULT_PING_TIMEOUT_IN_MS)
                    .errorHandler(errorHandler)
                    .build());

This is always returning false, but just in Android P. Any other version works fine.

I read about Android P is restricting network status access and I'm not sure if there can be a problem related to that, what do you guys think? Have any of you found a similar issue and respective solution?

Thanks in advance!

**Comment by pwittchen** [comment]
Hi @danielbeleza,

Thanks for reporting this issue, I'll verify it on Android P.
Can you provide any resource regarding network status access on Android P? 
It may be helpful during resolving this issue.

Regards,
Piotr

**Comment by danielbeleza** [comment]
Thanks for the quick response! 

There isn't any error or exception being throwed. The thing is it simply returns false, and our app reacts according to that response. In our case we show a no connection screen.

If I use the NetworkInfo class to get access to connectivity, it returns true, and everything works fine.

**Comment by pwittchen** [comment]
I haven't investigated it yet, but I have two suggestions for now:

1. Ensure you have appropriate permissions in your AndroidManifest.xml file:

```xml
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.INTERNET"/>
```

2. Try to change strategy for observing Internet connection. Default strategy is `WalledGardenInternetObservingStrategy` and maybe this implementation has some issues related to Android P. There's also another strategy called `SocketInternetObservingStrategy`. You can set it via `InternetObservingSettings` as follows:

```java
InternetObservingSettings
  .strategy(new SocketInternetObservingStrategy())
  .host(...)
  .port(...)
  ... // other settings go here
  .build()
```

Moreover, you can also use `observeNetworkConnectivity(...)` method, which checks network connectivity only (most WiFi networks have an Internet access, but they don't have to).

**Comment by danielbeleza** [comment]
I had already implemented the first suggestion, but not the second. Even so, it didn't work. 

We really want to validate more than just the network connectivity, but for now, we will use it as a workaround. I look forward for any updated on this.

Thank you for your help! 
Best regards,
Daniel Beleza

**Comment by herald25** [comment]
up for this I can't receive return value in Android P.

**Comment by pwittchen** [comment]
@herald25 What do you mean by "I can't receive return value"? This observable should return a value. Either `true` or `false`. Depending on timeout, remote server and its latency, you can receive value sooner or later.

**Comment by pwittchen** [comment]
Okay,

I know, what's going on.
In the debug I get the following error:

```
Cleartext HTTP traffic not permitted
```

It's related to the security issues. Starting with Android 9.0 (API level 28), cleartext support is disabled by default.

The quickfix will be setting `usesCleartextTraffic` to `true` in the `application` tag in `AndroidManifest.xml`

```xml
<application
  ...
  android:usesCleartextTraffic="true" >
```

You can check this commit: https://github.com/pwittchen/ReactiveNetwork/commit/f1b21baf1a1794706f56675a55f51939baedd4b6 to see how it's done in the sample apps.

You can also read about more details and other options of dealing with this problem here: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

I've added task in #300 regarding documentation of this thing.

I think, it's clear now and we can close this issue.

**Comment by MikolajKakol** [comment]
hi, @pwittchen sorry for bothering but wouldn't it better/enough just to switch to 

> http**s**://clients3.google.com/generate_204
in https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/library/src/main/java/com/github/pwittchen/reactivenetwork/library/rx2/internet/observing/strategy/WalledGardenInternetObservingStrategy.java
or add ability to switch to https?

**Comment by pwittchen** [comment]
Hi @MikolajKakol,

Thanks for your message. I think issue discussed in this topic is just related to Android P and clearTextTraffic. Generating 204 code with Google service may be not enough in that case since Android P.

**Comment by MikolajKakol** [comment]
Ok, I thought that on Android P would be enough to replace any clear text communication with secure one. I'm getting on emulator:
>     java.io.IOException: Cleartext HTTP traffic to clients3.google.com not permitted

Why wouldn't changing to https in `WalledGardenInternetObservingStrategy` fix this issue?

**Comment by pwittchen** [comment]
Hm, you may be right. according to the [documentation](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted), replacing `http` with `https` in https://github.com/pwittchen/ReactiveNetwork/blob/40b725013b8412289f56fec2601c4cab3f0fc76f/library/src/main/java/com/github/pwittchen/reactivenetwork/library/rx2/internet/observing/strategy/WalledGardenInternetObservingStrategy.java#L41 may fix this issue. I'll check that.
