### ISSUE TITLE
connection always return false(not connected)  SDK28 

### ISSUE THREAD

**Issue by MrRossi82** [pwittchen/ReactiveNetwork#309]
I test library this work all android versions but sdk 28 not working always return false not connected
this my code 

  @Override protected void onResume() {
        super.onResume();

        internetDisposable = ReactiveNetwork.observeInternetConnectivity()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(isConnected -> {

                    if (isConnected){

                            Toast.makeText(this,"Connected",Toast.LENGTH_LONG).show();

                    } else {

                        Toast.makeText(this,"Not Connected",Toast.LENGTH_LONG).show();

                    }
                        }

                );
    }

    @Override protected void onPause() {
        super.onPause();
        safelyDispose(internetDisposable);
    }

    private void safelyDispose(Disposable... disposables) {
        for (Disposable subscription : disposables) {
            if (subscription != null && !subscription.isDisposed()) {
                subscription.dispose();
            }
        }
    }

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. It's probably related to ClearText traffic
configuration, which needs to be done in AndroidManifest.xml since API 28.
Check documentation here:
https://github.com/pwittchen/ReactiveNetwork/blob/RxJava2.x/README.md#cleartext-traffic

sob., 20 paź 2018, 14:22 użytkownik Ahmad AlRahahleh <
notifications@github.com> napisał:

**Comment by jclova** [comment]
I notice similar behaviour on Android 9.0.
I am actually using 0.1X.X (RxJava 1.x).
Up to version 0.10.0, it works on Android 9.0. 
However, 0.11.0~0.12.4 it does not work on Android 9.0.

Adding 'android:usesCleartextTraffic="true"' at the AndroidManifest.xml does not help.

**Comment by pwittchen** [comment]
Hi @jclova. Currently RxJava 1.x version is no longer developed as well as original RxJava 1.x project. Nevertheless, you can try to apply different internet observing strategy. See this part of the documentation: https://github.com/pwittchen/ReactiveNetwork#internet-observing-strategies. It may be also an issue with the host you are pinging. You can also try to switch to RxJava2.x version as it may have more fixed bugs and solved issues than the older version.

**Comment by pwittchen** [comment]
RxJava1.x is no longer maintained and I don't see further issues with RxJava2.x branch, so I'm closing this one.
