### ISSUE TITLE
Unserialized access to connectivitySubject in MarshmallowNetworkObservingStrategy

### ISSUE THREAD

**Issue by aperfilyev** [pwittchen/ReactiveNetwork#313]
Basically, ```android.net.ConnectivityManager.NetworkCallback``` is invoked on ```android.net.ConnectivityThread``` by default and ```android.content.BroadcastReceiver#onReceive``` from idle mode is invoked on the main thread.

From RxJava doc:

> Calling onNext(Object), onError(Throwable) and onComplete() is required to be serialized (called from the same thread or called non-overlappingly from different threads through external means of serialization). The toSerialized() method available to all Subjects provides such serialization and also protects against reentrance (i.e., when a downstream Observer consuming this subject also wants to call onNext(Object) on this subject recursively).

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting that. I'll have a look at it.

Regards,
Piotr
