### ISSUE TITLE
checkInternetConnectivity() and observeInternetConnectivity() always return FALSE in Android 9

### ISSUE THREAD

**Issue by abir-hasan** [pwittchen/ReactiveNetwork#319]
Description: **checkInternetConnectivity()** and **observeInternetConnectivity()** always return FALSE in **Android 9**. While it was giving right information when my device was in Android 8.1.

I called the **checkInternetConnectivity** and **observeInternetConnectivity** from the from the **onCreate** method of my test-activity. They were returning false. Then I wrote this piece of code to see if I was doing something wrong:

> private fun checkBasicInternet() {
        val conManager: ConnectivityManager = applicationContext.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        val networkInfo: NetworkInfo? = conManager.activeNetworkInfo
        if (networkInfo != null && networkInfo.isConnected) {
            Log.d(TAG, "checkBasicInternet(): Connected")
        } else {
            Log.e(TAG, "checkBasicInternet(): Not Connected")
        }
    }

But this piece of code from same **onCreate()** returning correct result.

 - Device: [Mi A1]
 - OS: [Android 9]
 - Library Version: [3.0.2]

**Comment by abir-hasan** [comment]
Another thing which i found was when i called **observeInternetConnectivity** i get this in the log:

> E/ReactiveNetwork: Could not establish connection with WalledGardenStrategy
    java.io.IOException: Cleartext HTTP traffic to clients3.google.com not permitted

**This is occurring probably because:** Starting with Android 9.0 (API level 28), cleartext support is disabled by default.

Stackoverflow [Link](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted)

**Comment by pwittchen** [comment]
You need to customize clearText traffic in your app. It's described in the library documentation here: https://github.com/pwittchen/ReactiveNetwork#cleartext-traffic.

**Comment by pwittchen** [comment]
@abir-hasan have fixed it by enabling clearText traffic?

**Comment by abir-hasan** [comment]
> @abir-hasan have fixed it by enabling clearText traffic?

Sorry for the late response. I used option#2 to resolve the issue. Thanks.
