### ISSUE TITLE
Check Server is online or not [NOT WORKING]

### ISSUE THREAD

**Issue by Zulqurnain** [pwittchen/ReactiveNetwork#324]
**Server Online or Not**
it is always returning false in connectivity no matter what.

**To Reproduce**
Here is concise function i wrote to check if server is online or not. which is not working
 ```
public void observeServerURL(){
       String urlString = "http://www.someserver.com";

       if(urlString == null || urlString.isEmpty())return;
       InternetObservingSettings settings = InternetObservingSettings.builder()
               .strategy(new SocketInternetObservingStrategy())
               .host(urlString)
               .timeout(2000)
               .interval(10 * 1000) // each 10 seconds
               .initialInterval(1000)
               .build();
               ReactiveNetwork
                       .observeInternetConnectivity(settings)
                       .subscribeOn(Schedulers.io())
                       .observeOn(AndroidSchedulers.mainThread())
                       .subscribe(
                               isOnline -> {
                                   LogUtils.d("checking URL status:"+urlString+" , its online:"+isOnline);
                                   }
                               },
                               Throwable::printStackTrace
                       );
}
```

**Smartphone (please complete the following information):**
 - Device: OPPO
 - OS: 5.1
 - Library Version: 3.0.2

**Comment by pwittchen** [comment]
Thanks for reporting this. I'll check it. Are you sure, your server is
working and your device is connected to the network with Internet
connection? You can also check another strategy (Walled Garden)

czw., 28 lut 2019, 11:57 użytkownik Zulqurnain Haider <
notifications@github.com> napisał:

**Comment by Zulqurnain** [comment]
@pwittchen yeah I've checked Walled strategy its giving same results

**Comment by Zulqurnain** [comment]
Any news on this , i was going to integrate this in my app ?

**Comment by pwittchen** [comment]
I couldn't reproduce your issue. Maybe it's an issue in your app? You can verify that by running sample projects from this repo. If they works for you, then it must be an issue with your app. Moreover, I don't know what `cpp.add(...)` stands for in your context. Maybe this is a source of the problems?

**Comment by Zulqurnain** [comment]
Ok, I updated the code and removed that cpp.add() , because it was just a CompositeDisposable of rxjava , can you try on some test server except `google` ? because for my server it always give response in logcat for `[getaddrinfo]: hostname=myservername.com; servname=(null); netid=0; mark=0` like this

**Comment by pwittchen** [comment]
Then something may be wrong with your server. Moreover, in `InternetObservingSettings` you can set  `httpResponse(200)` (status: OK) if this is response status of your server. Default response in the settings is `HttpURLConnection.HTTP_NO_CONTENT` (204), which is the case in pinging `http://clients3.google.com/generate_204` in `WalledGardenInternetObservingStrategy`.

**Comment by pwittchen** [comment]
@Zulqurnain Did setting HTTP status helped in your case?

**Comment by Zulqurnain** [comment]
I just got an update from my backend team, they have disabled pinging on the server, is it somehow related to the issues?

**Comment by pwittchen** [comment]
Yes. This feature of the library pings the server.

**Comment by Zulqurnain** [comment]
I have found a solution for now, below code works with my server
```
private static boolean isURLReachable(String serverURL) {
        ConnectivityManager cm = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
        if(cm == null)return false;

        NetworkInfo netInfo = cm.getActiveNetworkInfo();
        if (netInfo != null && netInfo.isConnected()) {
            try {
                URL url = new URL(serverURL);   // Insert Url
                HttpURLConnection urlc = (HttpURLConnection) url.openConnection();
                urlc.setConnectTimeout(10 * 1000);          // 10 s.
                urlc.connect();
                if (urlc.getResponseCode() == 200) {        // 200 = "OK" code (http connection is fine).
                    Log.wtf("Connection", "Success !");
                    return true;
                } else {
                    return false;
                }
            } catch (MalformedURLException e1) {
                return false;
            } catch (IOException e) {
                return false;
            }
        }
        return false;
    }
```
but the library doesn't work, rest is up to you @pwittchen, hope you can debug the issue or add the functionality for server online detect for the server who have pinging disabled.

but my issue is not resolved by this library !!
