### ISSUE TITLE
Include library in pure java module

### ISSUE THREAD

**Issue by tsironis13** [pwittchen/ReactiveNetwork#326]
Hi,

how can i include the library in a pure java module?
I have tried the following: 
**'implementation 'com.github.pwittchen:reactivenetwork-rx2:3.0.2''**
but it is not working.

Thanks.

**Comment by pwittchen** [comment]
Hi,

This library cannot be included in a pure java module. It's an Android library, not a Java library and it relies on the classes from the Android API.

Regards,
Piotr
