### ISSUE TITLE
observing internet alwasys returning false

### ISSUE THREAD

**Issue by burhankhanzada** [pwittchen/ReactiveNetwork#329]
When I observe to internet connectivity is always get false also when using single.

    private var mDisposableNetwork: Disposable? = null
    private var mDisposableInternet: Disposable? = null

    override fun onResume() {
        super.onResume()
        // subscribe to ReactiveNetwork Network & Internet observers
        subscribeNetworkInternetConnectivity()
    }

    override fun onPause() {
        super.onPause()
        // unsubscribe to ReactiveNetwork Network Observers
        safelyDispose(mDisposableNetwork!!)
        mFragmentViewPager.notifyPagerInvisible()
    }

    private fun toggleNetworkInternetConnectionStatusBar() {
        if (!isNetworkConnected) {
            if (mLinearLayoutNetworkStatus.isGone()) {
                mLinearLayoutNetworkStatus.visiable()
            }
            mLinearLayoutNetworkStatus.setBackgroundColor(ContextCompat.getColor(this, R.color.noNetworkRed))
            mTintedProgressBarNetworkStatus.gone()
            mImageViewNetworkStatus.visiable()
            mTextViewNetworkStatus.text = resources.getString(R.string.network_status_no_network)
        } else {
            if (!isActiveInternet) {
                mLinearLayoutNetworkStatus.setBackgroundColor(ContextCompat.getColor(this, R.color.checkingForActiveInterConnectionAmber))
                mImageViewNetworkStatus.gone()
                mTintedProgressBarNetworkStatus.visiable()
                mTextViewNetworkStatus.text = resources.getString(R.string.network_status_checking)
            } else {
                mLinearLayoutNetworkStatus.setBackgroundColor(ContextCompat.getColor(this, R.color.activeInternetConnectionGreen))
                mTintedProgressBarNetworkStatus.gone()
                mImageViewNetworkStatus.gone()
                mTextViewNetworkStatus.text = resources.getString(R.string.network_status_connected)

                // wait for 2 seconds before hide network status bar
                val handler = Handler()
                handler.postDelayed({
                    mLinearLayoutNetworkStatus.gone()
                }, 2000)
            }
        }
    }

    private fun subscribeNetworkInternetConnectivity() {

        val internetObservable = ReactiveNetwork.observeInternetConnectivity()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())

        // check internet connectivity once
        val internetSingle = ReactiveNetwork.checkInternetConnectivity()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())

        mDisposableNetwork = ReactiveNetwork.observeNetworkConnectivity(applicationContext)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe { connectivity ->
                    if (connectivity.state() == NetworkInfo.State.CONNECTED) {

                        isNetworkConnected = true

                        toggleNetworkInternetConnectionStatusBar()

    //                        internetSingle.subscribe { isConnectedToInternet ->
    //
    //                            isActiveInternet = isConnectedToInternet
    //
    //                            toggleNetworkInternetConnectionStatusBar()
    //
    //                        }

                        mDisposableInternet = internetObservable.subscribe { isConnectedToInternet ->

                            Log.e(TAG, "isInternetConnected $isConnectedToInternet")

                            isActiveInternet = isConnectedToInternet

                            toggleNetworkInternetConnectionStatusBar()

                        }

                        safelyDispose(mDisposableInternet!!)

                    } else if (connectivity.state() == NetworkInfo.State.DISCONNECTED) {

                        isNetworkConnected = false

                        toggleNetworkInternetConnectionStatusBar()

                    }
                }

    }

    // method to safely dispose one or more disposables
    private fun safelyDispose(vararg disposables: Disposable) {
        for (subscription in disposables) {
            if (!subscription.isDisposed) {
                subscription.dispose()
            }
        }
    }

**Expected behavior**
I am expecting true in observe internet.

**Comment by pwittchen** [comment]
There's too much code in this snippet. I suppose your application's logic may be wrong. Moreover, you are saving state in the variable, which is not good idea and may be the source of problems. Try to check sample apps from this repository. Are they returning wrong results for you?

**Comment by burhankhanzada** [comment]
well after @pwittchen recommend to check sample apps so it was working fine so then I did some debugging in my own app and found in that it was an error that is `E/ReactiveNetwork: Could not establish connection with WalledGardenStrategy
    java.io.IOException: Cleartext HTTP traffic to clients3.google.com not permitted` because android 9 pie and later they disabled the cleartext support so to solve this problem I just add this `android:usesCleartextTraffic="true"` in application body in manifest and its just work fine like in android version below from 9 @pwittchen  you must add this in the readme

**Comment by pwittchen** [comment]
Hi,

Thanks for the message. It's already in Readme.

--
Piotr Wittchen,
http://wittchen.io

niedz., 21 kwi 2019, 00:23 użytkownik Burhan Khanzada <
notifications@github.com> napisał:

**Comment by burhankhanzada** [comment]
oh sorry i didn't see that
