### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by ychescale9** [pwittchen/ReactiveNetwork#331]
Currently this is the last dependency in our project that requires us to turn on Jetifier. It would be great if we can migrate its support-lib dependencies to AndroidX. Happy to send a PR. 😃

**Comment by pwittchen** [comment]
Hi!

Sure. I have to check, which packages needs to be migrated and if they influence the library code in any way or its just a package re-naming. If you'd like to send a PR, go ahead :).

Regards,
Piotr
