### ISSUE TITLE
checking internet connectivity is not working on android Q

### ISSUE THREAD

**Issue by holoc285** [pwittchen/ReactiveNetwork#415]

**Comment by pwittchen** [comment]
Thank you for reporting this issue. What **exactly** doesn't work? Any details?

**Comment by kothsada** [comment]
it is checking internet status always false

**Comment by eslam2010011** [comment]
+1

**Comment by pwittchen** [comment]
Do you have any stacktrace? Does it relate to network checking or just internet checking? Are you sure that your internet connectivity is reliable? What methods from the API are you using? Any code snippets?

**Comment by pwittchen** [comment]
It may be related to #422

**Comment by pwittchen** [comment]
I changed default port from https to http in default host for internet checking in PR #425. Https stopped working for default host for some reason and changing port didn't help. It should fix this issue.

**Comment by pwittchen** [comment]
It should be fixed now. Bug-fix will be available in the next release.

**Comment by holoc285** [comment]
Thanks in advance. @pwittchen

**Comment by pwittchen** [comment]
@holoc285 bug fix is already released in version 3.0.8 for RxJava 2. This bug should not occur in this version. If you still have it, then please report it.
