### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by SleepLe33** [pwittchen/ReactiveNetwork#472]
**Describe the bug**

**To Reproduce**

or create a failing unit test (recommended)

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Library Version: [e.g. 3.0.0]

**Additional context**

**Comment by pwittchen** [comment]
There's no description of the problem.
