### ISSUE TITLE
Is android.permission.ACCESS_COARSE_LOCATION really needed?

### ISSUE THREAD

**Issue by agatti** [pwittchen/ReactiveNetwork#50]
Hi there,

  as per subject, is ACCESS_COARSE_LOCATION really needed to be requested by applications using ReactiveNetwork?  I've tried to remove it on a custom build of the library and it doesn't seem to cause any ill effects, but maybe I'm missing something here...

Thank you!

**Comment by pwittchen** [comment]
It's needed if we want to observe WiFi access points. For just observing connectivity it's actually not needed. We can think of managing this permission in a better way or extracting WiFi monitoring functionality to a separate library.

**Comment by pwittchen** [comment]
For now, you can use such solution to override this permission in your app: http://stackoverflow.com/questions/27962789/android-gradle-manifest-merger-override-uses-permission-attribute-coming-from

**Comment by agatti** [comment]
I see...  Indeed I only use the library for checking the connectivity status.  Interestingly enough, the latest Android Studio lint didn't spot the problem when removing said permission (whilst complaining when removing any of the other ones).

I wonder if it would be possible to only have said permission if building for anything earlier than API23 and switch to a request-permission model otherwise, but probably it'd be adding a bit too much complexity on something self-contained such as ReactiveNetwork and that it's doing its job flawlessly otherwise :)

Anyway, I'll take a look at the SO link you mention, and thanks a lot for clarifying the issue so quickly.

Feel free to close this issue if you see fit, then :)

**Comment by pwittchen** [comment]
I know about permission model in Android 6, but I also want to keep compatibility with Android 4 and up for now, because some people still use it. Moreover, I think that handling permission requests shouldn't be part of the library.

Thanks for your question. Feel free to ask more, if you have any doubts. :)

**Comment by pwittchen** [comment]
After merging PR #67 to the master branch, this permission can be removed from the Manifest of the library. In release v. 0.4.0, this permission will be no longer needed.

**Comment by pwittchen** [comment]
Removed by PR #67.
