### ISSUE TITLE
Is android.permission.CHANGE_WIFI_STATE really needed?

### ISSUE THREAD

**Issue by sregg** [pwittchen/ReactiveNetwork#52]
and if so, for what purpose?

**Comment by pwittchen** [comment]
Hi. I needed it to implement one of the library functionalities. To be honest, right now I don't remember, which one. Probably it's related to observing WiFi access points. I'll investigate it later and give you more concrete answer.

**Comment by pwittchen** [comment]
Maybe it'll be good idea to extract observing WiFi access points functionality to a separate library, because issue #50 is similar to this one. It should reduce number of required permissions.

**Comment by sregg** [comment]
Yes that would be a good idea to sepparate the features
I managed to remove the unnecessary permissions using
`<uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:node="remove"/>`

**Comment by pwittchen** [comment]
After merging PR #67, this permission can be removed from the Manifest of the library.
In release 0.4.0 this permission will be no longer needed.

**Comment by pwittchen** [comment]
Permission removed by PR #67.
