### ISSUE TITLE
Update to  RxJava 2.0.0

### ISSUE THREAD

**Issue by epicstar** [pwittchen/ReactiveNetwork#80]
I think it may be time to update ReactiveNetwork to use RxJava 2.x.

RxJava 2.0.0 RC1 is now out: https://github.com/ReactiveX/RxJava/releases/tag/v2.0.0-RC1

In addition, RxAndroid 2.0.0 RC1 is also out: https://github.com/ReactiveX/RxAndroid/releases/tag/2.0.0-RC1

I haven't looked at the new version, but how much effort is it to update ReactiveNetwork to use RxJava 2.0.0?

**Comment by pwittchen** [comment]
I know about RC release of RxJava 2.0.0, but I haven't taken a look on that and its release notes. I'll check it out and write more detailed information about the future upgrade.

**Comment by pwittchen** [comment]
Resources, which may be useful during library migration to RxJava 2.0:
- https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0
- https://github.com/akarnokd/RxJava2Interop

I think, we can work on migration on a separate git branch, but new release of the library, when RxJava will be officially released and will be no longer RC.

**Comment by pwittchen** [comment]
I've created branch `update-to-rxjava2`. I'll be working on this branch in order to prepare the library for RxJava 2.0.0.

**Comment by pwittchen** [comment]
We need to upgrade RxAndroid at the same time as well: https://github.com/ReactiveX/RxAndroid/releases/tag/2.0.0-RC1.

**Comment by pwittchen** [comment]
As far as I see, it won't be that easy to rewrite library code to RxJava2. They removed and renamed a lot of methods and classes in the public API, so I need to dig deep into code and documentation, to migrate library correctly. I started migration locally today, but it's not going as smoothly as I expected, so it may take some time. It also needs to be tested afterwards.

**Comment by Rainer-Lang** [comment]
Maybe this helps 
https://medium.com/@amitshekhar/migrating-from-rxjava1-to-rxjava2-5dac0a94b4aa

**Comment by pwittchen** [comment]
Hello again everyone,

I migrated library code and sample apps to RxJava 2.0.0-RC1 and RxAndroid 2.0.0-RC1.
Currently, this is experimental code as both RxJava and RxAndroid released their Release Candidates.
If you want to test it or check it out, see [RxJava2.x](https://github.com/pwittchen/ReactiveNetwork/tree/RxJava2.x) branch in this repository.

**Comment by tushar-acharya** [comment]
@pwittchen I've raised a pull request with latest changes at #164 Let me know if you want any changes there.

**Comment by pwittchen** [comment]
Hi @tushar-acharya, 

Thanks for the comment. I wrote a response in your PR.

**Comment by pwittchen** [comment]
It's done. ReactiveNetwork with support for RxJava2.x will be available in the next release as a separate artifact `reactivenetwork-rx2`. Now it's available on `RxJava2.x` branch.
