### ISSUE TITLE
Idea: Releasing two separate artifacts (library modules) for RxJava 1.x and RxJava 2.x

### ISSUE THREAD

**Issue by pwittchen** [pwittchen/ReactiveNetwork#84]
Hello,

I'm creating this issue for the record. It's related to issue #80. RxJava 2.x is in now in RC and its API was massively changed comparing to RxJava 1.x. I want to keep compatibility in this library with RxJava 2.x, but I know a lot of developers will use RxJava 1.x for some time because migration is not that easy and is related to external dependencies. Some apps may use reactive libraries, which haven't been migrated to RxJava 2.x, what may cause compatibility problems or additional work to keep interoperability with two different versions of RxJava. I already have coded library version compatible with RxJava 2.x on a separate branch. I think, it may be a good idea to create a separate library module for RxJava 2.x with new artifact id like `reactivenetwork-rxjava2`. Moreover, it will require separate documentation in `README.md` file. I also thought about some kind of adapters, but the code of the ReactiveNetwork Observables is strongly dependent on RxJava API. Actually, it's tightly coupled to it. I don't know if it's possible to decouple this code, because it's build out of reactive stuff. I don't want to abandon RxJava 1.x completely now, but I want to be up to date with RxJava 2.x as well. That's why I came with an idea of a separate module. I'm open to any other ideas and suggestions. You can write here what do you think about it. Is it good or bad idea or if you know any better solutions for that.

Regards,
Piotr

**Comment by jackmalpo** [comment]
What's the status on this?

**Comment by pwittchen** [comment]
Hi, @jackmalpo. I'm planning, to do it soon (hopefully this month) right after resolving two bugs/improvements waiting in "to do" list.

**Comment by tushar-acharya** [comment]
@pwittchen I've raised a pull request with latest changes at #164 Let me know if you want any changes there.

**Comment by pwittchen** [comment]
Hi,

Thanks for the comment. I wrote the response in your PR.

**Comment by pwittchen** [comment]
Separate artifact for RxJava2.x will be available in the next release.
