### ISSUE TITLE
Close the socket in the internet check

### ISSUE THREAD

**Issue by Kisty** [pwittchen/ReactiveNetwork#91]
I think the socket should be closed here, else isn't it leaking memory?

https://github.com/pwittchen/ReactiveNetwork/blob/master/library/src/main/java/com/github/pwittchen/reactivenetwork/library/ReactiveNetwork.java#L131

**Comment by pwittchen** [comment]
It can be a good idea. Nevertheless, in this case, we are constantly checking this socket connection in a given interval, so I think it's better to leave it open while the subscription is active. Socket connection can be closed while unsubscribing the Observable. Then, it would be the right improvement.

**Comment by Kisty** [comment]
OK. But surely it's opening a new socket every ping and leaving the connection open per ping is only going to accumulate sockets open or do they not work in that way?

**Comment by pwittchen** [comment]
I need to investigate or debug it to be sure about exact behavior. After an investigation, we can apply correct improvement. E.g. closing socket on unsubscribe or add finally block for doing that.
