### ISSUE TITLE
Create Observables with Observable.fromEmitter() instead of Observable.create()

### ISSUE THREAD

**Issue by epicstar** [pwittchen/ReactiveNetwork#92]
I've noticed that the source code uses `Observable.create()`  methods to either create observables on:
- Broadcast receivers for broadcasted network events (pre-lollipop)
- network callbacks (lollipop+)

I've been following talks on RxJava, and one of the biggest sins today is the use of `Observable.create()`. Using this operator to create observables means that you know that you are creating an operator from scratch... from error checking to backpressure.

Instead, the library should be using the newer operators [Observable.fromEmitter()](http://reactivex.io/RxJava/javadoc/rx/Observable.html#fromEmitter%28rx.functions.Action1,%20rx.AsyncEmitter.BackpressureMode%29) and possibly [Observable.fromCallable()](http://reactivex.io/RxJava/javadoc/rx/Observable.html#fromCallable%28java.util.concurrent.Callable%29) which have things baked into them to handle all edge cases so that you only have to worry about implementing the basic parts of the observable.

This article explains the use-cases of each operator well: http://www.pacoworks.com/2016/08/21/this-is-not-an-rxjava-tutorial/

In addition, the god @JakeWharton goes into great detail on using the newer operators and why 99% of developers will not want to use `Observable.create()` for observable creation: http://fragmentedpodcast.com/episodes/053-jake-wharton-on-rxjava-2/

Ideally, the library should be using `Observable.fromEmitter()` for both Networking strategies. This operator is a bridge for callback functions to get their operations into the observable world. But maybe perhaps `Observable.fromCallable()` may be worth a read, also.

**Comment by epicstar** [comment]
As an addendum to the description, I would consider this a bit of a high priority. The library will greatly benefit from using the newer operators.

**Comment by pwittchen** [comment]
Thanks for creating this issue. I'll take a look on that. Any ideas for improvements are welcome.

**Comment by akarnokd** [comment]
FYI, `Observable.fromEmitter` is deprecated and is scheduled for removal in 1.3. Use the `Observable.create(Action<Emitter<T>>, Emitter.BackpressureMode)` instead.

**Comment by pwittchen** [comment]
@akarnokd Thanks for the information! Right now, this library is not using `Observable.fromEmmiter`, so it's good to know to avoid using it in the future.

**Comment by pwittchen** [comment]
Due to the last comments, I'm closing this issue. I created a new one for possible refactoring.
